services:
  app:
    build:
      dockerfile: Dockerfile.app
      target: dev
    volumes:
      - '.:/var/app'
    ports:
      - "8000:8000"
  node:
    build:
      dockerfile: Dockerfile.node
      target: dev
    volumes:
      - '.:/var/app'
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && npm run dev"
    ports:
      - "5173:5173"
